accent = "#38404f"
cursor = "#D0D0D0"
foreground = "#E1E1E1"
background = "#151515"
selection_foreground = "#E1E1E1"
selection_background = "#373737"

color0 = "#151515"
color1 = "#b46958"
color2 = "#90A959"
color3 = "#FFA557"
color4 = "#BAD7FF"
color5 = "#AA749F"
color6 = "#A2B5C1"
color7 = "#373737"
color8 = "#727272"
color9 = "#b46958"
color10 = "#181B18"
color11 = "#F4BF75"
color12 = "#7E97AB"
color13 = "#AA759F"
color14 = "#88afa2"
color15 = "#AFAFAF"
