$activeBorderColor = rgb(38404f)
$inactiveBorderColor = rgb(151515)
$activeBorderBlend = rgb(7E97AB)
# $activeBorderColor = rgba(38404f) rgba(7E97AB) 45deg

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    # col.active_border = $activeBorderColor $activeBorderBlend 45deg
}

group {
    col.border_active = $activeBorderColor
}
